kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: thanos-cluster
nodes:
  - role: control-plane
  # - role: worker
  # - role: worker  
  # - role: worker
  # - role: worker

# Add Docker options for insecure registries
# containerdConfigPatches:
#   - |
#     [plugins."io.containerd.grpc.v1.cri".registry]
#       [plugins."io.containerd.grpc.v1.cri".registry.configs."registry:5000"]
#         [plugins."io.containerd.grpc.v1.cri".registry.configs."registry:5000".auth]
#         # no authentication needed for insecure registry



# create local registry
# docker run -d -p 5005:5000 --network kind --restart=always --name registry registry:2