apiVersion: v1
kind: Pod
metadata:
  name: netutils-pod
  labels:
    app: netutils
spec:
  containers:
  - name: netutils
    image: nicolaka/netshoot     # This image contains networking troubleshooting tools
    command:
    - sleep
    - "3600"                     # Keep the container running for 1 hour
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"