apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: miladmohammadi27/project:latest
        ports:
        - containerPort: 9090 # Application port
        - containerPort: 9095 # Metrics port
        envFrom:
        - configMapRef:
            name: project-config-map
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"


