apiVersion: v1
kind: Service
metadata:
  name: project-nodeport-service
  namespace: development
spec:
  selector:
    app: project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
    nodePort: 30001
  type: NodePort  

---

apiVersion: v1
kind: Service
metadata:
  name: project-clusterip-service
  namespace: development
spec:
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP