apiVersion: v1
kind: ServiceAccount
metadata:
  name: cockroachdb
  namespace: cockroach  # Add your namespace
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-master
  namespace: cockroach
  labels:
    app: cockroachdb-master
spec:
  ports:
  - port: 26257
    name: grpc
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: cockroachdb-master
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-master-node-port
  namespace: cockroach 
  labels:
    app: cockroachdb-master
spec:
  type: NodePort
  ports:
  - port: 26257
    targetPort: 26257
    name: grpc
    nodePort: 30000
  - port: 8080
    targetPort: 8080
    name: http
    nodePort: 31080
  selector:
    app: cockroachdb-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb-master
  namespace: cockroach
spec:
  serviceName: cockroachdb-master
  replicas: 2
  selector:
    matchLabels:
      app: cockroachdb-master
  template:
    metadata:
      labels:
        app: cockroachdb-master
    spec:
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:v22.2.8
        command:
          - "/bin/bash"
          - "-c"
          - |
            cockroach start \
            --join=cockroachdb-master-0.cockroachdb-master,cockroachdb-master-1.cockroachdb-master \
            --advertise-addr=$(hostname).cockroachdb-master \
            --insecure --http-addr=0.0.0.0:8080 \
            --listen-addr=0.0.0.0 \
            --cluster-name=distributed-cluster
        ports:
        - containerPort: 26257
          name: grpc
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: cockroachdb-data
          mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
  - metadata:
      name: cockroachdb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

# initialize cluster just in one pod
# /cockroach/cockroach init --insecure --cluster-name=distributed-cluster