apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-slave
  namespace: cockroach
  labels:
    app: cockroachdb-slave
spec:
  ports:
  - port: 26257
    name: grpc
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: cockroachdb-slave
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-slave-node-port
  namespace: cockroach 
  labels:
    app: cockroachdb-slave
spec:
  type: NodePort
  ports:
  - port: 26257
    targetPort: 26257
    name: grpc
    nodePort: 30001
  - port: 8080
    targetPort: 8080
    name: http
    nodePort: 31081
  selector:
    app: cockroachdb-slave
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb-slave
  namespace: cockroach
spec:
  serviceName: cockroachdb-slave
  replicas: 3
  selector:
    matchLabels:
      app: cockroachdb-slave
  template:
    metadata:
      labels:
        app: cockroachdb-slave
    spec:
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:v22.2.8
        command:
          - "/bin/bash"
          - "-c"
          - |
            cockroach start \
            --join=cockroachdb-master-0.cockroachdb-master,cockroachdb-master-1.cockroachdb-master \
            --advertise-addr=$(hostname).cockroachdb-slave \
            --insecure \
            --http-addr=0.0.0.0:8080 \
            --listen-addr=0.0.0.0 \
            --cluster-name=distributed-cluster
        ports:
        - containerPort: 26257
          name: grpc
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: cockroachdb-data
          mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
  - metadata:
      name: cockroachdb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
