apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        cluster: "cluster-two" 
        region: "us-east"   
    scrape_configs:
      - job_name: 'project'
        scheme: http
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - development
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: ${1}:9095
            action: replace
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: project