apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 10901          # gRPC port
      targetPort: 10901    # port where the sidecar is listening
      nodePort: 31000     # specify a NodePort or let Kubernetes assign one
  selector:
    app: prometheus
