apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    http {
        upstream backend {
            server cluster-one-control-plane:30001 weight=50;  # 50% of the traffic
            server cluster-two-control-plane:30001 weight=50;  # 50% of the traffic
        }

        server {
            listen 80;

            location / {
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }

    events {
        worker_connections 1024;  # Adjust based on your needs
    }

