apiVersion: v1
kind: Service
metadata:
  name: nginx-api-gateway
spec:
  type: NodePort  # or NodePort, depending on your setup
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
